### ISSUE TITLE
NullPointerException during container information gather

### ISSUE THREAD

**Issue by aschmid13** [CA-APM/caworld-docker#1]
Might be related to some containers name? If I disable the following property, it succeeds:

docker.show.container.info=false

Only happens in one of our Docker environments as well.

[INFO] [com.ca.apm.fieldpacks.docker.DataPoller] Total no of containers found : 152
java.lang.NullPointerException
        at com.ca.apm.fieldpacks.docker.DataPoller.makeMetric(DataPoller.java:908)
        at com.ca.apm.fieldpacks.docker.DataPoller.makeMetrics(DataPoller.java:840)
        at com.ca.apm.fieldpacks.docker.DataPoller.makeMetrics(DataPoller.java:817)
        at com.ca.apm.fieldpacks.docker.DataPoller.run(DataPoller.java:591)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by ggrossbe** [comment]
Hi Alex,

I'll send you a build with a fix. Can you send me an email?

The reason for the NPE is that the container state does not match any of the expected values.

Ciao,
Guenter
